CREATE SCHEMA IF NOT EXISTS player_info;
CREATE SCHEMA IF NOT EXISTS match_info;
CREATE SCHEMA IF NOT EXISTS static;

CREATE TABLE IF NOT EXISTS player_info."players" (
    "player_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "steam_id" BIGINT NOT NULL,
    "prof_name" VARCHAR(255),
    "nickname" VARCHAR(255),
    "rank" SMALLINT
    PRIMARY KEY("player_id")
) TABLESPACE data_space;

COMMENT ON TABLE player_info."players" IS 'Игроки, участвующие в матчах Dota 2';
COMMENT ON COLUMN player_info."players"."steam_id" IS 'Ссылка на аккаунт Steam игрока';
COMMENT ON COLUMN player_info."players"."prof_name" IS 'Профессиональное имя игрока';
COMMENT ON COLUMN player_info."players"."rank" IS 'Matchmaking место в топе игрока';
COMMENT ON COLUMN player_info."players"."nickname" IS 'Никнейм игрока в игре';

------------------------------------------------------

CREATE TABLE IF NOT EXISTS "static"."heroes" (
    "hero_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "hero_name" VARCHAR(255),
    "attribute" VARCHAR(255),
    "attack_type" BOOLEAN,
    PRIMARY KEY("hero_id")
) TABLESPACE data_space;

COMMENT ON TABLE "static"."heroes" IS 'Герои Dota 2';
COMMENT ON COLUMN "static"."heroes"."hero_name" IS 'Название героя';
COMMENT ON COLUMN "static"."heroes"."attribute" IS 'Основной атрибут героя (Strength, Agility, Intelligence)';
COMMENT ON COLUMN "static"."heroes"."attack_type" IS 'Тип атаки: дальний (TRUE) или ближний (FALSE)';

------------------------------------------------------

CREATE TABLE IF NOT EXISTS "static"."items" (
    "item_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "item_name" VARCHAR(255),
    "cost" INTEGER,
    "recipe" TEXT,
    PRIMARY KEY("item_id")
) TABLESPACE data_space;

COMMENT ON TABLE "static"."items" IS 'Предметы, доступные для покупки в игре';
COMMENT ON COLUMN "static"."items"."item_name" IS 'Название предмета';
COMMENT ON COLUMN "static"."items"."cost" IS 'Стоимость предмета в золоте';
COMMENT ON COLUMN "static"."items"."recipe" IS 'Компоненты или рецепт предмета';

------------------------------------------------------

CREATE TABLE IF NOT EXISTS "static"."neutral_items" (
    "neutral_items_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "neutral_items_name" VARCHAR(255) NOT NULL,
    "tier" SMALLINT,
    PRIMARY KEY("neutral_items_id")
) TABLESPACE data_space;

COMMENT ON TABLE "static"."neutral_items" IS 'Нейтральные предметы, выпадающие в игре';
COMMENT ON COLUMN "static"."neutral_items"."neutral_items_name" IS 'Название нейтрального предмета';
COMMENT ON COLUMN "static"."neutral_items"."tier" IS 'Уровень (ранг) нейтрального предмета';

------------------------------------------------------

CREATE TABLE IF NOT EXISTS "static"."neutral_enchant" (
    "neutral_enchant_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "neutral_enchant_name" VARCHAR(255),
    PRIMARY KEY("neutral_enchant_id")
) TABLESPACE data_space;

COMMENT ON TABLE "static"."neutral_enchant" IS 'Энчанты (усиления) для нейтральных предметов';
COMMENT ON COLUMN "static"."neutral_enchant"."neutral_enchant_name" IS 'Название усиления';

------------------------------------------------------

CREATE TABLE IF NOT EXISTS match_info."matches" (
    "match_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "duration" INTEGER,
    "winner" BOOLEAN,
    "date" DATE NOT NULL,
    PRIMARY KEY("match_id")
) TABLESPACE data_space;

COMMENT ON TABLE match_info."matches" IS 'Информация о сыгранных матчах';
COMMENT ON COLUMN match_info."matches"."duration" IS 'Продолжительность матча в секундах';
COMMENT ON COLUMN match_info."matches"."winner" IS 'Победившая сторона: Radiant (FALSE) или Dire (TRUE)';
COMMENT ON COLUMN match_info."matches"."date" IS 'Дата проведения матча';

------------------------------------------------------

CREATE TABLE IF NOT EXISTS match_info."player_match_stat" (
    "stat_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "match_id" BIGINT NOT NULL,
    "player_id" BIGINT NOT NULL,
    "hero_id" INTEGER NOT NULL,
    "side" BOOLEAN NOT NULL,
    "pos" VARCHAR(255),
    "kills" SMALLINT NOT NULL DEFAULT 0,
    "deaths" SMALLINT NOT NULL DEFAULT 0,
    "assists" SMALLINT NOT NULL DEFAULT 0,
    "gpm" SMALLINT NOT NULL DEFAULT 0,
    "xpm" SMALLINT NOT NULL DEFAULT 0,
    "last_hit" SMALLINT NOT NULL DEFAULT 0,
    "denies" SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY("stat_id")
) TABLESPACE data_space;

COMMENT ON TABLE match_info."player_match_stat" IS 'Статистика игроков в конкретных матчах';
COMMENT ON COLUMN match_info."player_match_stat"."match_id" IS 'Ссылка на матч';
COMMENT ON COLUMN match_info."player_match_stat"."player_id" IS 'Ссылка на игрока';
COMMENT ON COLUMN match_info."player_match_stat"."hero_id" IS 'Герой, выбранный игроком';
COMMENT ON COLUMN match_info."player_match_stat"."side" IS 'Сторона: Radiant (FALSE) или Dire (TRUE)';
COMMENT ON COLUMN match_info."player_match_stat"."pos" IS 'Позиция игрока на линии';
COMMENT ON COLUMN match_info."player_match_stat"."kills" IS 'Количество убийств';
COMMENT ON COLUMN match_info."player_match_stat"."deaths" IS 'Количество смертей';
COMMENT ON COLUMN match_info."player_match_stat"."assists" IS 'Количество ассистов';
COMMENT ON COLUMN match_info."player_match_stat"."gpm" IS 'Золото в минуту';
COMMENT ON COLUMN match_info."player_match_stat"."xpm" IS 'Опыт в минуту';
COMMENT ON COLUMN match_info."player_match_stat"."last_hit" IS 'Количество добитых крипов';
COMMENT ON COLUMN match_info."player_match_stat"."denies" IS 'Количество денайев';

------------------------------------------------------

CREATE TABLE IF NOT EXISTS match_info."player_items" (
    "player_items_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "stat_id" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL,
    "time_from_start" INTEGER NOT NULL,
    PRIMARY KEY("player_items_id")
) TABLESPACE data_space;

COMMENT ON TABLE match_info."player_items" IS 'Предметы, купленные игроком в ходе матча';
COMMENT ON COLUMN match_info."player_items"."stat_id" IS 'Ссылка на статистику игрока в матче';
COMMENT ON COLUMN match_info."player_items"."item_id" IS 'Ссылка на предмет';
COMMENT ON COLUMN match_info."player_items"."time_from_start" IS 'Время покупки от начала матча (в секундах)';

------------------------------------------------------

CREATE TABLE IF NOT EXISTS match_info."player_neutral_items" (
    "player_neutral_items_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "stat_id" INTEGER NOT NULL,
    "neutral_item_id" INTEGER NOT NULL,
    "neutral_enchant_id_" INTEGER NOT NULL,
    "time_from_start" INTEGER NOT NULL,
    "tier" SMALLINT,
    PRIMARY KEY("player_neutral_items_id")
) TABLESPACE data_space;

COMMENT ON TABLE match_info."player_neutral_items" IS 'Нейтральные предметы и энчанты, полученные игроком';
COMMENT ON COLUMN match_info."player_neutral_items"."stat_id" IS 'Ссылка на статистику игрока в матче';
COMMENT ON COLUMN match_info."player_neutral_items"."neutral_item_id" IS 'Ссылка на нейтральный предмет';
COMMENT ON COLUMN match_info."player_neutral_items"."neutral_enchant_id_" IS 'Ссылка на энчант предмета';
COMMENT ON COLUMN match_info."player_neutral_items"."time_from_start" IS 'Время получения предмета от начала матча';
COMMENT ON COLUMN match_info."player_neutral_items"."tier" IS 'Уровень нейтрального предмета';

------------------------------------------------------

CREATE TABLE IF NOT EXISTS player_info."steam_account" (
    "steam_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "login" VARCHAR(255) NOT NULL,
    "full_name" VARCHAR(255),
    "nickname" VARCHAR(255) NOT NULL,
    "country" VARCHAR(255),
    "birthday" DATE,
    PRIMARY KEY("steam_id")
) TABLESPACE data_space;

COMMENT ON TABLE player_info."steam_account" IS 'Учётные записи Steam, связанные с игроками';
COMMENT ON COLUMN player_info."steam_account"."login" IS 'Логин пользователя в Steam';
COMMENT ON COLUMN player_info."steam_account"."full_name" IS 'Полное имя пользователя';
COMMENT ON COLUMN player_info."steam_account"."nickname" IS 'Игровой никнейм пользователя';
COMMENT ON COLUMN player_info."steam_account"."country" IS 'Страна пользователя';
COMMENT ON COLUMN player_info."steam_account"."birthday" IS 'Дата рождения';

------------------------------------------------------

-- Внешние ключи
-- 🔗 Внешние ключи с указанием схем

ALTER TABLE match_info."player_match_stat"
    ADD FOREIGN KEY("hero_id")
    REFERENCES static."heroes"("hero_id")
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE match_info."player_items"
    ADD FOREIGN KEY("stat_id")
    REFERENCES match_info."player_match_stat"("stat_id")
    ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE match_info."player_items"
    ADD FOREIGN KEY("item_id")
    REFERENCES static."items"("item_id")
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE match_info."player_neutral_items"
    ADD FOREIGN KEY("stat_id")
    REFERENCES match_info."player_match_stat"("stat_id")
    ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE match_info."player_neutral_items"
    ADD FOREIGN KEY("neutral_item_id")
    REFERENCES static."neutral_items"("neutral_items_id")
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE player_info."players"
    ADD FOREIGN KEY("steam_id")
    REFERENCES player_info."steam_account"("steam_id")
    ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE match_info."player_match_stat"
    ADD FOREIGN KEY("player_id")
    REFERENCES player_info."players"("player_id")
    ON UPDATE RESTRICT ON DELETE SET NULL;

ALTER TABLE match_info."player_match_stat"
    ADD FOREIGN KEY("match_id")
    REFERENCES match_info."matches"("match_id")
    ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE match_info."player_neutral_items"
    ADD FOREIGN KEY("neutral_enchant_id")
    REFERENCES static."neutral_enchant"("neutral_enchant_id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE INDEX CONCURRENTLY idx_matches_match_id
ON match_info.matches (match_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_player_match_stat_match_id
ON match_info.player_match_stat (match_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_player_match_stat_player_id
ON match_info.player_match_stat (player_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_player_match_stat_hero_id
ON match_info.player_match_stat (hero_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_player_items_item_id
ON match_info.player_items (item_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_player_neutral_items_neutral_item_id
ON match_info.player_neutral_items (neutral_item_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_player_neutral_items_neutral_enchant_id
ON match_info.player_neutral_items (neutral_enchant_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_players_player_id
ON player_info.players (player_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_players_steam_id
ON player_info.players (steam_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_steam_account_steam_id
ON player_info.steam_account (steam_id)
TABLESPACE index_space;

CREATE INDEX CONCURRENTLY idx_steam_account_login
ON player_info.steam_account (login)
TABLESPACE index_space;
